# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
