# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20170312_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=32768, unique=True),
        ),
    ]
