# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_auto_20170312_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=32768),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='uid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
